-- Requête SQL pour ajouter les colonnes à la table houses

ALTER TABLE houses
ADD COLUMN IF NOT EXISTS bedrooms INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS bathrooms INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS area_sqm DECIMAL(10,2),

-- Équipements
ADD COLUMN IF NOT EXISTS air_conditioning BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS heating BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS hot_water BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS internet BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS parking BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS elevator BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS balcony BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS garden BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pool BOOLEAN DEFAULT FALSE,

-- Sécurité
ADD COLUMN IF NOT EXISTS security_cameras BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS alarm_system BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS interphone BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS guardian BOOLEAN DEFAULT FALSE,

-- Informations financières
ADD COLUMN IF NOT EXISTS deposit_amount DECIMAL(15,2),
ADD COLUMN IF NOT EXISTS agency_fees DECIMAL(15,2),
ADD COLUMN IF NOT EXISTS utilities_included BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS utilities_amount DECIMAL(15,2),

-- Conditions de location
ADD COLUMN IF NOT EXISTS minimum_rental_period INTEGER,
ADD COLUMN IF NOT EXISTS availability_date DATE,
ADD COLUMN IF NOT EXISTS pets_allowed BOOLEAN,
ADD COLUMN IF NOT EXISTS smoking_allowed BOOLEAN,

-- Informations de localisation avancées
ADD COLUMN IF NOT EXISTS neighborhood TEXT,
ADD COLUMN IF NOT EXISTS property_type TEXT,
ADD COLUMN IF NOT EXISTS floor INTEGER,
ADD COLUMN IF NOT EXISTS furnished BOOLEAN DEFAULT FALSE,

-- Environnement
ADD COLUMN IF NOT EXISTS proximity_transport TEXT,
ADD COLUMN IF NOT EXISTS proximity_schools TEXT,
ADD COLUMN IF NOT EXISTS proximity_shops TEXT,
ADD COLUMN IF NOT EXISTS proximity_green_spaces TEXT,

-- Métadonnées
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
